- src/Application.php
- src/Component.php
- tests/functional/DatadirTest.php
- tests/functional/TestManager.php
- tests/functional/migrate-simple-transformation/setUp.php
- tests/functional/migrate-simple-transformation/tearDown.php
- tests/traits/GetTransformation.php
Jira - https://keboola.atlassian.net/browse/COM-725
> mark old transformation as migrated

- src/ValueObjects/TransformationV2.php
- tests/functional/migrate-transformations-with-storage/expected/data/out/transformationDump/transformations.json
- tests/functional/migrate-transformations-with-storage/setUp.php
Jira - https://keboola.atlassian.net/browse/COM-744
> rename input mapping keys

- src/Application.php
- src/Component.php
- src/TransformationValidator.php
- src/ValueObjects/TransformationV2.php
- tests/functional/migrate-multi-transformation-backends/expected-stdout
- tests/functional/migrate-multi-transformation-phases/expected-stdout
- tests/functional/migrate-multi-transformations/expected-stdout
- tests/functional/migrate-simple-transformation/expected-stdout
- tests/functional/migrate-transformations-with-packages/expected-stdout
- tests/functional/migrate-transformations-with-storage/expected-stdout
- tests/phpunit/TransformationValidatorTest.php
- tests/traits/CreateTransformationTrait.php
- tests/traits/GetTransformation.php
- tests/traits/RemoveTrasformationTrait.php
Jira - https://keboola.atlassian.net/browse/COM-832
> Change response & fix empty transformation

- src/Configuration/Config.php
- src/TransformationValidator.php
- tests/phpunit/TransformationValidatorTest.php
https://keboola.slack.com/archives/CQ1ASK06M/p1620916223164900?thread_ts=1620657462.116500&cid=CQ1ASK06M
> convert unsupported backend type to user error and check it

- src/ValueObjects/TransformationV2.php
- tests/functional/migrate-transformations-with-storage/setUp.php
Jira - https://keboola.atlassian.net/browse/COM-887
> strip out `loadType`

- src/Application.php
- tests/functional/migrate-simple-transformation/tearDown.php
Slack - https://keboola.slack.com/archives/CQ1ASK06M/p1623737189095300
> set changeDescription to old transformation after migrated

- src/TransformationValidator.php
- tests/phpunit/TransformationValidatorTest.php
Jira:
- https://keboola.atlassian.net/browse/COM-890
- https://keboola.atlassian.net/browse/COM-897
> Better checking empty configuration

- deploy.sh
- src/TransformationValidator.php
- tests/phpunit/TransformationValidatorTest.php
zapomněl jsem načíst github_tags + jedno typo na opravu
> GitHub actions + typo

- src/Application.php
- src/ValueObjects/TransformationV2.php
- src/ValueObjects/TransformationV2Block.php
- tests/functional/migrate-multi-transformation-backends/expected/data/out/transformationDump/transformations.json
- tests/functional/migrate-multi-transformation-phases/expected/data/out/transformationDump/transformations.json
- tests/functional/migrate-multi-transformations/expected/data/out/transformationDump/transformations.json
- tests/functional/migrate-simple-transformation/expected/data/out/transformationDump/transformations.json
- tests/functional/migrate-transformations-with-file-tags/expected/data/out/transformationDump/transformations.json
- tests/functional/migrate-transformations-with-packages/expected/data/out/transformationDump/transformations.json
- tests/functional/migrate-transformations-with-storage/expected/data/out/transformationDump/transformations.json
Jira - https://keboola.atlassian.net/browse/COM-894
> 1 phase = 1 transformation block

- src/Component.php
- src/StorageApiClientFactory.php
- tests/phpunit/StorageApiClientFactoryTest.php
Jira - https://keboola.atlassian.net/browse/COM-913
> Migration in dev branch

- src/Application.php
- tests/functional/migrate-multi-transformation-phases/setUp.php
- tests/traits/CreateTransformationTrait.php
Jira - https://keboola.atlassian.net/browse/COM-889
problém je popsaný v komentáři v Jiře
> Fix transformation name

- src/ValueObjects/TransformationV2.php
- tests/functional/migrate-transformations-with-storage/expected/data/out/transformationDump/transformations.json
- tests/functional/migrate-transformations-with-storage/setUp.php
Jira - https://keboola.atlassian.net/browse/COM-914
Slack - https://keboola.slack.com/archives/CQ1ASK06M/p1624262949002000
> dataType=clone - not migrate columns & datatypes

- src/TransformationValidator.php
- tests/phpunit/TransformationValidatorTest.php
slack - https://keboola.slack.com/archives/CQ1ASK06M/p1624259979001400
> Change error message

- src/ValueObjects/TransformationV2.php
- tests/functional/migrate-transformations-with-storage/expected/data/out/transformationDump/transformations.json
- tests/functional/migrate-transformations-with-storage/setUp.php
Slack - https://keboola.slack.com/archives/CQ1ASK06M/p1624447678013200
> convert column_types object -> array

- src/Application.php
- tests/functional/completion-input-mapping-from-storage/expected/data/out/transformationDump/transformations.json
- tests/functional/completion-input-mapping-from-storage/setUp.php
Slack - https://keboola.slack.com/archives/CQ1ASK06M/p1626944695033400?thread_ts=1626869904.025800&cid=CQ1ASK06M
> fix completion Input Mapping from storage metadata

- src/Application.php
- src/ValueObjects/TransformationV2.php
Slack - https://keboola.slack.com/archives/CQ1ASK06M/p1626953749038600?thread_ts=1626869904.025800&cid=CQ1ASK06M
> set length to null if not exists in config

- src/Application.php
- src/ValueObjects/TransformationV2.php
- tests/functional/migrate-multi-transformation-phases/expected-stdout
- tests/functional/migrate-multi-transformation-phases/expected/data/out/transformationDump/transformations.json
- tests/functional/sorting-transformations/expected-stdout
- tests/functional/sorting-transformations/expected/data/out/transformationDump/transformations.json
Jira - https://keboola.atlassian.net/browse/COM-1003
> Splitting transformations via phases

- src/Application.php
- src/ValueObjects/TransformationV2.php
- tests/functional/completion-input-mapping-from-storage/expected/data/out/transformationDump/transformations.json
- tests/functional/completion-input-mapping-from-storage/setUp.php
Jira - https://keboola.atlassian.net/browse/COM-1017
> Fix bug - null column metadata

- src/Application.php
- tests/functional/sorting-transformations/setUp.php
Jira - https://keboola.atlassian.net/browse/COM-1024
> Fix bug: dependency not found

- src/ValueObjects/TransformationV2.php
- tests/functional/merge-columns-combine-tables-columns/expected/data/out/transformationDump/transformations.json
- tests/functional/merge-columns-combine-tables-columns/setUp.php
- tests/functional/merge-columns-first-full-columns/expected/data/out/transformationDump/transformations.json
- tests/functional/merge-columns-first-full-columns/setUp.php
- tests/functional/merge-columns-second-full-columns/expected/data/out/transformationDump/transformations.json
- tests/functional/merge-columns-second-full-columns/setUp.php
Jira - https://keboola.atlassian.net/browse/COM-1027
V předchozím PR #35 jsem udělal jen mergování pro `column_types` a musíme mergnout ještě `columns`
> Merge IM columns

- src/LegacyTransformationHelper.php
- tests/functional/completion-input-mapping-from-storage/expected/data/out/transformationDump/transformations.json
Jira - https://keboola.atlassian.net/browse/COM-1153
> Sort columns in IM

- src/ValueObjects/TransformationV2.php
- tests/functional/migrate-simple-transformation/tearDown.php
https://keboola.slack.com/archives/CMTBFNLF8/p1638873566235100
> Change transformation name
